version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - '5433:5432' # Map host port 5433 to container port 5432
    environment:
      - POSTGRES_USER=cameron
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=ecommerce-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
