name: ecommerce_local_pg_database

services:
  db:
    container_name: postgres_local_db
    image: postgres:16
    ports:
      - '5433:5432' # Map host port 5433 to container port 5432
    environment:
      - POSTGRES_USER=cameron
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=ecommerce-db
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

volumes:
  postgres_local_data:
