name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce_prod_app:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce_prod_app:latest
            sudo docker stop ecommerce_prod_app || true
            sudo docker rm ecommerce_prod_app || true
            sudo docker run -d --name ecommerce_prod_app -p 4000:4000 \
              -e PORT=${{ secrets.PORT }} \
              -e NODE_ENV=${{ secrets.NODE_ENV }} \
              -e SEED=${{ secrets.SEED }} \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e AWS_S3_REGION=${{ secrets.AWS_S3_REGION }} \
              -e AWS_S3_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESS_KEY_ID }} \
              -e AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }} \
              -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
              -e PRODUCT_SEED_PRODUCT_URL=${{ secrets.PRODUCT_SEED_PRODUCT_URL }} \
              -e CATEGORY_IMAGES_SEED_URL=${{ secrets.CATEGORY_IMAGES_SEED_URL }} \
              -e ADMIN_FIRST_NAME=${{ secrets.ADMIN_FIRST_NAME }} \
              -e ADMIN_LAST_NAME=${{ secrets.ADMIN_LAST_NAME }} \
              -e ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
              -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
              -e ADMIN_PHONE=${{ secrets.ADMIN_PHONE }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce_prod_app:latest
