name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce_prod_app:latest

      - name: Write SSH key to file securely
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
        shell: bash

      - name: Check SSH access
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo SSH connection successful" || { echo 'SSH failed'; exit 1; }
        shell: bash

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: key.pem
          target: /home/ubuntu/key.pem

      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key_path: /home/ubuntu/key.pem
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce_prod_app:latest
            docker stop ecommerce_prod_app || true
            docker rm ecommerce_prod_app || true
            docker run -d --name ecommerce_prod_app -p 4000:4000 \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e SEED=${{ secrets.SEED }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce_prod_app:latest
